/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminaldevendas1;

import javax.swing.table.DefaultTableModel;


public class Terminal extends javax.swing.JFrame {

    private Cliente cliente = new Cliente(0, "", "", "");
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    private Produto produto = new Produto(0,"", 0,"");
    public void setProduto(Produto produto){
        this.produto = produto;
    }
    
    double valortotal = 0;
    
    public Terminal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jBcodcli = new javax.swing.JButton();
        jTcodcli = new javax.swing.JTextField();
        jTcliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jBcodprod = new javax.swing.JButton();
        jTcodprod = new javax.swing.JTextField();
        jTproduto = new javax.swing.JTextField();
        jTqnt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jBadicionar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBfinalizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTtotal = new javax.swing.JTextField();
        jTdinheiro = new javax.swing.JTextField();
        jTtroco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 550));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("VENDA DE PRODUTOS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Produto", "Valor", "QTD", "Total"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.setRowHeight(24);
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Cod. Cliente:");

        jBcodcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        jBcodcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcodcliActionPerformed(evt);
            }
        });

        jTcodcli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTcodcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcodcliActionPerformed(evt);
            }
        });
        jTcodcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTcodcliKeyReleased(evt);
            }
        });

        jTcliente.setEditable(false);
        jTcliente.setBackground(new java.awt.Color(255, 255, 153));
        jTcliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Cod. Produto:");

        jBcodprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        jBcodprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcodprodActionPerformed(evt);
            }
        });

        jTcodprod.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTcodprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTcodprodKeyReleased(evt);
            }
        });

        jTproduto.setEditable(false);
        jTproduto.setBackground(new java.awt.Color(255, 255, 153));
        jTproduto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jTqnt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTqnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTqntActionPerformed(evt);
            }
        });
        jTqnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTqntKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Quantidade:");

        jBadicionar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBadicionar.setText("Adicionar");
        jBadicionar.setEnabled(false);
        jBadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBadicionarActionPerformed(evt);
            }
        });
        jBadicionar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBadicionarKeyPressed(evt);
            }
        });

        jBcancelar.setBackground(new java.awt.Color(255, 102, 102));
        jBcancelar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBcancelar.setForeground(new java.awt.Color(255, 51, 0));
        jBcancelar.setText("Cancelar Venda");
        jBcancelar.setBorder(null);
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBfinalizar.setBackground(new java.awt.Color(102, 255, 102));
        jBfinalizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBfinalizar.setForeground(new java.awt.Color(0, 153, 51));
        jBfinalizar.setText("Finalizar Venda");
        jBfinalizar.setBorder(null);
        jBfinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfinalizarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Total:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Dinheiro:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Troco:");

        jTtotal.setEditable(false);
        jTtotal.setBackground(new java.awt.Color(255, 255, 153));
        jTtotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTtotal.setForeground(new java.awt.Color(255, 0, 0));

        jTdinheiro.setEditable(false);
        jTdinheiro.setBackground(new java.awt.Color(255, 255, 255));
        jTdinheiro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTdinheiro.setForeground(new java.awt.Color(102, 102, 102));
        jTdinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTdinheiroKeyPressed(evt);
            }
        });

        jTtroco.setEditable(false);
        jTtroco.setBackground(new java.awt.Color(255, 255, 153));
        jTtroco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTtroco.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBcodcli, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTcodcli, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBcodprod, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTcodprod, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTqnt)))
                            .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTproduto, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jBadicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBfinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTtroco, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jTdinheiro)
                            .addComponent(jTtotal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBcodcli)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTcodcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBcodprod)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTcodprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTqnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jBadicionar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBfinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTdinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTtroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTqntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTqntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTqntActionPerformed

    private void jBfinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfinalizarActionPerformed
        dispose();
    }//GEN-LAST:event_jBfinalizarActionPerformed

    private void jTcodcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcodcliActionPerformed
    }//GEN-LAST:event_jTcodcliActionPerformed

    private void jBcodcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcodcliActionPerformed
        BuscaCliente2 busc = new BuscaCliente2(this, true);
        busc.setVisible(true);
        int codSelecionado = busc.getCodSelecionado();
        jTcodcli.setText(""+codSelecionado);
        buscarCliente();
    }//GEN-LAST:event_jBcodcliActionPerformed

    private void jBcodprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcodprodActionPerformed
        BuscaProduto2 bus = new BuscaProduto2(this, true);
        bus.setVisible(true);
        int codSelecionado = bus.getCodSelecionado();
        jTcodprod.setText(""+codSelecionado);
        buscarProduto();
    }//GEN-LAST:event_jBcodprodActionPerformed

    private void jTcodcliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcodcliKeyReleased
        String texto = jTcodcli.getText();
        buscarCliente();
        jTcodcli.setEnabled(false);
    }//GEN-LAST:event_jTcodcliKeyReleased

    private void jTcodprodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcodprodKeyReleased
        String texto = jTcodprod.getText();
        buscarProduto();
    }//GEN-LAST:event_jTcodprodKeyReleased

    private void jBadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBadicionarActionPerformed
        double valor = Double.parseDouble(jTqnt.getText()) * produto.getValor();
        this.valortotal += valor; 
        jTtotal.setText(String.valueOf(valortotal));
            
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        Object[] valores = {produto.getCod(), produto.getProduto(), produto.getValor(), jTqnt.getText(), valor};
        dtm.addRow(valores);
        jBcancelar.setEnabled(true);
        jTdinheiro.setEditable(true);
            
        jTcodprod.setText("");
        jTproduto.setText("");
        jTqnt.setText("");
    }//GEN-LAST:event_jBadicionarActionPerformed

    private void jBadicionarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBadicionarKeyPressed

    }//GEN-LAST:event_jBadicionarKeyPressed

    private void jTqntKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTqntKeyReleased
        if (jTqnt.getText()!= null && jTcodcli != null && jTcodprod != null){
            jBadicionar.setEnabled(true);
        }else {
            jBadicionar.setEnabled(false);
        }
    }//GEN-LAST:event_jTqntKeyReleased

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        limpa();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jTdinheiroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdinheiroKeyPressed
        double total = valortotal;
        if (evt.getKeyCode() == 10){
        double dinheiro = Double.parseDouble(jTdinheiro.getText());
        double troco = dinheiro - valortotal;
        jTtroco.setText(""+String.format("%.2f", troco));
        jBfinalizar.setEnabled(true);
        Finalizar fim = new Finalizar(cliente, total, dinheiro, troco, this);
        fim.setVisible(true);
        }
    }//GEN-LAST:event_jTdinheiroKeyPressed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBadicionar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBcodcli;
    private javax.swing.JButton jBcodprod;
    private javax.swing.JButton jBfinalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTcliente;
    private javax.swing.JTextField jTcodcli;
    private javax.swing.JTextField jTcodprod;
    private javax.swing.JTextField jTdinheiro;
    private javax.swing.JTextField jTproduto;
    private javax.swing.JTextField jTqnt;
    private javax.swing.JTextField jTtotal;
    private javax.swing.JTextField jTtroco;
    // End of variables declaration//GEN-END:variables

    public void buscarCliente(){
        String texto = jTcodcli.getText();
        setCliente (new Cliente(0,"","",""));
        
        Inicio.clientes.forEach((cliente) ->{
            if (texto == null ? cliente.getCod()+"" == null : texto.equals(cliente.getCod()+"")){
                setCliente(cliente);
            }
        });
        
        if (this.cliente.getCod() != 0){
            jTcliente.setText(this.cliente.getCod() +" - " +this.cliente.getNome());
        } else {
            jTcliente.setText("Não existe");
            setCliente( new Cliente(0,"","",""));
        }
    }
    
    public void buscarProduto(){
        String texto = jTcodprod.getText();
        setProduto (new Produto(0,"",0,""));
        
        Inicio.produtos.forEach((produto) ->{
            if (texto == null ? produto.getCod()+"" == null : texto.equals(produto.getCod()+"")){
                setProduto(produto);
            }
        });
        
        if (this.produto.getCod() != 0){
            jTproduto.setText(this.produto.getCod() +" - " +this.produto.getProduto());
        } else {
            jTproduto.setText("Não existe");
            setCliente( new Cliente(0,"","",""));
        }
    }
    
    public void limpa(){
        setCliente(new Cliente(0, "", "", ""));
        setProduto(new Produto(0, "", 0, ""));
        jTcliente.setText("");
        jTproduto.setText("");
        this.valortotal = 0;
        jTtotal.setText("");
        jTdinheiro.setText("");
        jTtroco.setText("");
        jTcodcli.setText("");
        jTcodprod.setText("");
        jTqnt.setText("");
        jTcodcli.setEnabled(true);
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        for (int i = jTable1.getRowCount(); i > 0; i--) {
            dtm.removeRow(i-1);
        }
    }
}
