/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author mrmat
 */
public class Calculadora extends javax.swing.JFrame {
    
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtela = new javax.swing.JLabel();
        jBlimpa = new javax.swing.JButton();
        jBsete = new javax.swing.JButton();
        jBquatro = new javax.swing.JButton();
        jBum = new javax.swing.JButton();
        jBvezes = new javax.swing.JButton();
        jBzero = new javax.swing.JButton();
        jBdois = new javax.swing.JButton();
        jBoito = new javax.swing.JButton();
        jBcinco = new javax.swing.JButton();
        jBtres = new javax.swing.JButton();
        jBnove = new javax.swing.JButton();
        jBseis = new javax.swing.JButton();
        jBmenos = new javax.swing.JButton();
        jBmais = new javax.swing.JButton();
        jBigual = new javax.swing.JButton();
        jBdividido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLtela.setBackground(new java.awt.Color(0, 204, 204));
        jLtela.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLtela.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLtela.setOpaque(true);

        jBlimpa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBlimpa.setText("Limpar");
        jBlimpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpaActionPerformed(evt);
            }
        });

        jBsete.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBsete.setText("7");
        jBsete.setMaximumSize(new java.awt.Dimension(79, 79));
        jBsete.setMinimumSize(new java.awt.Dimension(79, 79));
        jBsete.setPreferredSize(new java.awt.Dimension(79, 79));
        jBsete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseteActionPerformed(evt);
            }
        });

        jBquatro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBquatro.setText("4");
        jBquatro.setMaximumSize(new java.awt.Dimension(79, 79));
        jBquatro.setMinimumSize(new java.awt.Dimension(79, 79));
        jBquatro.setPreferredSize(new java.awt.Dimension(79, 79));
        jBquatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBquatroActionPerformed(evt);
            }
        });

        jBum.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBum.setText("1");
        jBum.setMaximumSize(new java.awt.Dimension(79, 79));
        jBum.setMinimumSize(new java.awt.Dimension(79, 79));
        jBum.setPreferredSize(new java.awt.Dimension(79, 79));
        jBum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBumActionPerformed(evt);
            }
        });

        jBvezes.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBvezes.setText("X");
        jBvezes.setMaximumSize(new java.awt.Dimension(79, 79));
        jBvezes.setMinimumSize(new java.awt.Dimension(79, 79));
        jBvezes.setPreferredSize(new java.awt.Dimension(79, 79));
        jBvezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvezesActionPerformed(evt);
            }
        });

        jBzero.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBzero.setText("0");
        jBzero.setMaximumSize(new java.awt.Dimension(79, 79));
        jBzero.setMinimumSize(new java.awt.Dimension(79, 79));
        jBzero.setPreferredSize(new java.awt.Dimension(79, 79));

        jBdois.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBdois.setText("2");
        jBdois.setMaximumSize(new java.awt.Dimension(79, 79));
        jBdois.setMinimumSize(new java.awt.Dimension(79, 79));
        jBdois.setPreferredSize(new java.awt.Dimension(79, 79));
        jBdois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdoisActionPerformed(evt);
            }
        });

        jBoito.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBoito.setText("8");
        jBoito.setMaximumSize(new java.awt.Dimension(79, 79));
        jBoito.setMinimumSize(new java.awt.Dimension(79, 79));
        jBoito.setPreferredSize(new java.awt.Dimension(79, 79));
        jBoito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoitoActionPerformed(evt);
            }
        });

        jBcinco.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBcinco.setText("5");
        jBcinco.setMaximumSize(new java.awt.Dimension(79, 79));
        jBcinco.setMinimumSize(new java.awt.Dimension(79, 79));
        jBcinco.setPreferredSize(new java.awt.Dimension(79, 79));
        jBcinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcincoActionPerformed(evt);
            }
        });

        jBtres.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBtres.setText("3");
        jBtres.setMaximumSize(new java.awt.Dimension(79, 79));
        jBtres.setMinimumSize(new java.awt.Dimension(79, 79));
        jBtres.setPreferredSize(new java.awt.Dimension(79, 79));
        jBtres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtresActionPerformed(evt);
            }
        });

        jBnove.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBnove.setText("9");
        jBnove.setMaximumSize(new java.awt.Dimension(79, 79));
        jBnove.setMinimumSize(new java.awt.Dimension(79, 79));
        jBnove.setPreferredSize(new java.awt.Dimension(79, 79));
        jBnove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnoveActionPerformed(evt);
            }
        });

        jBseis.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBseis.setText("6");
        jBseis.setMaximumSize(new java.awt.Dimension(79, 79));
        jBseis.setMinimumSize(new java.awt.Dimension(79, 79));
        jBseis.setPreferredSize(new java.awt.Dimension(79, 79));
        jBseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseisActionPerformed(evt);
            }
        });

        jBmenos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBmenos.setText("-");
        jBmenos.setMaximumSize(new java.awt.Dimension(79, 79));
        jBmenos.setMinimumSize(new java.awt.Dimension(79, 79));
        jBmenos.setPreferredSize(new java.awt.Dimension(79, 79));
        jBmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmenosActionPerformed(evt);
            }
        });

        jBmais.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBmais.setText("+");
        jBmais.setMaximumSize(new java.awt.Dimension(79, 79));
        jBmais.setMinimumSize(new java.awt.Dimension(79, 79));
        jBmais.setPreferredSize(new java.awt.Dimension(79, 79));
        jBmais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmaisActionPerformed(evt);
            }
        });

        jBigual.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBigual.setText("=");
        jBigual.setMaximumSize(new java.awt.Dimension(79, 79));
        jBigual.setMinimumSize(new java.awt.Dimension(79, 79));
        jBigual.setPreferredSize(new java.awt.Dimension(79, 79));
        jBigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBigualActionPerformed(evt);
            }
        });

        jBdividido.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jBdividido.setText("/");
        jBdividido.setMaximumSize(new java.awt.Dimension(79, 79));
        jBdividido.setMinimumSize(new java.awt.Dimension(79, 79));
        jBdividido.setPreferredSize(new java.awt.Dimension(79, 79));
        jBdividido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdivididoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLtela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBquatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBsete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBvezes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBdois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBcinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBoito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBzero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBseis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBnove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBdividido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBmenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBmais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jBigual, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBlimpa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBlimpa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLtela, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBsete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBquatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBvezes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBoito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBcinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBdois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBzero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBnove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBseis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBmais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBmenos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBdividido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBigual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLtela.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBlimpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpaActionPerformed
        jLtela.setText("");
        Calculo.limpa();
    }//GEN-LAST:event_jBlimpaActionPerformed

    private void jBseteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBseteActionPerformed
        jLtela.setText(jLtela.getText()+"7");
    }//GEN-LAST:event_jBseteActionPerformed

    private void jBoitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoitoActionPerformed
        jLtela.setText(jLtela.getText()+"8");
    }//GEN-LAST:event_jBoitoActionPerformed

    private void jBnoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnoveActionPerformed
        jLtela.setText(jLtela.getText()+"9");
    }//GEN-LAST:event_jBnoveActionPerformed

    private void jBmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmaisActionPerformed
        if(jLtela.getText() != ""){
            Calculo.setV1(Double.parseDouble(jLtela.getText()));
            Calculo.setOperacao("mais");
            jLtela.setText("");
        }
    }//GEN-LAST:event_jBmaisActionPerformed

    private void jBtresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtresActionPerformed
        jLtela.setText(jLtela.getText()+"3");
    }//GEN-LAST:event_jBtresActionPerformed

    private void jBigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBigualActionPerformed
        Calculo.setV2(Double.parseDouble(jLtela.getText()));
        Calculo.calculaResultado();
        jLtela.setText(""+Calculo.getResult());
    }//GEN-LAST:event_jBigualActionPerformed

    private void jBvezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvezesActionPerformed
        if(jLtela.getText() != ""){
            Calculo.setV1(Double.parseDouble(jLtela.getText()));
            Calculo.setOperacao("vezes");
            jLtela.setText("");
        }
    }//GEN-LAST:event_jBvezesActionPerformed

    private void jBumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBumActionPerformed
        jLtela.setText(jLtela.getText()+"1");
    }//GEN-LAST:event_jBumActionPerformed

    private void jBdoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdoisActionPerformed
        jLtela.setText(jLtela.getText()+"2");
    }//GEN-LAST:event_jBdoisActionPerformed

    private void jBquatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBquatroActionPerformed
        jLtela.setText(jLtela.getText()+"4");
    }//GEN-LAST:event_jBquatroActionPerformed

    private void jBcincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcincoActionPerformed
        jLtela.setText(jLtela.getText()+"5");
    }//GEN-LAST:event_jBcincoActionPerformed

    private void jBseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBseisActionPerformed
        jLtela.setText(jLtela.getText()+"6");
    }//GEN-LAST:event_jBseisActionPerformed

    private void jBdivididoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdivididoActionPerformed
        if(jLtela.getText() != ""){
            Calculo.setV1(Double.parseDouble(jLtela.getText()));
            Calculo.setOperacao("dividido");
            jLtela.setText("");
        }
    }//GEN-LAST:event_jBdivididoActionPerformed

    private void jBmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmenosActionPerformed
        if(jLtela.getText() != ""){
            Calculo.setV1(Double.parseDouble(jLtela.getText()));
            Calculo.setOperacao("menos");
            jLtela.setText("");
        }
    }//GEN-LAST:event_jBmenosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBcinco;
    private javax.swing.JButton jBdividido;
    private javax.swing.JButton jBdois;
    private javax.swing.JButton jBigual;
    private javax.swing.JButton jBlimpa;
    private javax.swing.JButton jBmais;
    private javax.swing.JButton jBmenos;
    private javax.swing.JButton jBnove;
    private javax.swing.JButton jBoito;
    private javax.swing.JButton jBquatro;
    private javax.swing.JButton jBseis;
    private javax.swing.JButton jBsete;
    private javax.swing.JButton jBtres;
    private javax.swing.JButton jBum;
    private javax.swing.JButton jBvezes;
    private javax.swing.JButton jBzero;
    private javax.swing.JLabel jLtela;
    // End of variables declaration//GEN-END:variables
}
